export const API_URL = 'https://swinesouth.japfa.com.vn:62169/';
// export const API_URL = 'https://swinesouth.japfa.com.vn:62173/';
export const PRICE_API_URL = 'https://apps.japfa.com.vn:62048/api/';
export const MASTER_URL = 'https://e-approval1.japfa.com.vn:62070/api/';
export const AUTH_URL = 'http://apps.japfavietnam.com:62064/api/';

export const PASSCODE_SECRET_KEY = 'bdb51f41fba865ec';

export const masterConstant = {
  appID: 5,
  loginLog: true,
  clientID: 'l1s212242dfj2q234er57dsffswe',
};

const AppString = {
  Common: {
    ComingSoon: 'Chức năng đang được phát triển!',
    SelectDefault: 'Chọn',
    ConfirmTitle: 'Xác Nhận Thao Tác',
    ConfirmText: 'Bạn có chắc muốn thực hiện thao tác này ?',
    ConfirmAccept: 'Đồng Ý',
    ConfirmCancel: 'Bỏ Qua',
  },
  SO: {
    deleteDenied: 'Đơn hàng đã được chốt. Không thể xóa',
    postToDoSuccess: 'Đơn hàng đã được chốt đơn thành công',
    revertToSoSuccess: 'Đơn hàng đã được hủy chốt đơn',
    title: 'Danh Sách Đơn Hàng',
    search: 'Nhập tên khách hàng, mã đơn hàng.',
    modalFilterTitle: 'Thời Gian Bán Hàng',
    fromDate: 'Từ ngày',
    toDate: 'Đến ngày',
    filter: 'Lấy dữ liệu',
    NewOrder: 'Đơn hàng mới',
    closeOrder: 'Đơn hàng đã chốt',
    successOrder: 'Đơn hàng đã hoàn thành',
    CustomersOrderForm: 'Phiếu Đặt Khách Hàng',
    CustomerName: 'Khách Hàng',
    DeliveryDate: 'Ngày Giao',
    TruckNumber: 'Số Xe',
    DeliveryAddress: 'Địa Chỉ Giao Hàng',
    TimeToReceive: 'Thời Gian Nhận Hàng',
    Recipient: 'Người Nhận',
    RecipientsPhoneNumber: 'SĐT Người Nhận',
    FarmExport: 'Trại/ Kho xuất',
    AddProductTitle: 'Thêm Hàng Hóa',
    SummaryTitle: 'Tổng Hợp Thông Tin Đơn Hàng',
    Product: 'Hàng Hóa',
    ProductFilterPlaceholder: 'Nhập tên hoặc mã sản phẩm',
  },
  DO: {
    title: 'Đơn Hàng',
    titleModalSeach: 'Thời gian đơn hàng',
    search: 'Nhập tên khách hàng, mã đơn hàng.',
    newOrder: 'Đơn hàng mới',
    successOrder: 'Đơn hàng đã hoàn thành',
    createdInvoice: 'Đơn hàng đã lập hóa đơn',
    fromDate: 'Từ ngày',
    toDate: 'Đến ngày',
    DeliveryTitle: 'Yêu Cầu Giao Hàng',
    deleteSuccess: 'Xóa đơn hàng {0} thành công',
    farm: 'Trại/ Kho xuất',
    customerName: 'Khách Hàng',
    deliveryDate: 'Ngày giao',
    deliveryAddress: 'Địa chỉ giao hàng',
    truckNo: 'Số xe',
    deliveryTime: 'Thời gian nhận hàng',
    receiverName: 'Người nhận',
    receiverPhone: 'SĐT người nhận',
    saleMan: 'Nhân viên bán hàng',
    supervisor: 'Nhân viên giám sát',
    note: 'Ghi chú',
    submitTitle: 'Lưu Thông Tin',
    deleteProduct: 'Xóa sản phẩm thành công',
    postToInvoiceSuccess: 'Đơn hàng {0} đã được xử lý',
  },
  IN_TF: {
    title: 'Chuyển Nội Bộ',
  },
  Invoice: {
    title: 'Hóa Đơn',
    doTabTitle: 'Đơn Hàng',
    invoiceTabTitle: 'Hóa Đơn',
    modalFilterTitle: 'Thời gian đơn hàng',
    InValidView: 'Vui lòng phát hành hóa đơn trước!',
    DeleteMessage: 'Xóa đơn hàng thành công',
    PublishSuccess: 'Phát hành hóa đơn thành công',
    NewInvoice: 'Hóa đơn mới',
    PublishInvoice: 'Đã chuyển sang HĐ ĐT',
    CanceledInvoice: 'Hóa đơn đã hủy',
    CannotDelete: 'Hóa đơn đã được phát hành. Không thể xóa !',
    CancelSuccess: 'Hủy hóa đơn thành công',
  },
  Scale: {
    NewStatus: 'Phiếu Cân Mới',
    DeletedStatus: 'Phiếu Cân Đã Chốt',
  },
  Discount: {
    Title: 'Danh Sách Chiết Khấu',
    ModalFilterTitle: 'Thời gian chiết khấu',
    SearchPlaceHolder: 'Mã khách hàng, tên kh, mã chiết khấu',
    NewStatus: 'Chưa Được Phê Duyệt',
    ApprovedStatus: 'Đã Được Phê Duyệt',
    DetailTitle: 'Chi Tiêt Chiết Khấu',
    DeleteSuccess: 'Xóa chiết khấu {0} thành công.',
    postSuccess: 'Ghi sổ chiết khẩu {0} thành công.',
    returnPostSuccess: 'Huy ghi sổ chiết khấu {0} thành công',
    seachCustomer: 'Nhập tên khách hàng',
    unitModalTitle: 'Chọn Đơn Vị',
    discountTypeModalTitle: 'Chọn Loại Chiết Khấu',
    createSuccess: 'Tạo chiết khấu thành công',
    updateSuccess: 'Cập nhật chiết khấu thành công',
  },
  Cndn: {
    title: 'Điều Chỉnh',
    listSearchPlaceholder: 'Số chứng từ, tên khách hàng',
    filterModalTitle: 'Tìm kiếm theo thời gian',
    status: {
      new: 'Chưa duyệt',
      approved: 'Đã duyệt',
      invoiced: 'Đã lập hóa đơn',
      canceled: 'Từ chối duyệt',
    },
    titleCreate: 'Phiếu Điều Chỉnh',
    unDeleteMessage: 'Chứng từ đã được xử lý. Không thể xóa!',
    deleteHeader: (cndnNo: string) => `Xóa chứng từ ${cndnNo} thành công`,
    approveSuccess: (cndnNo: string) => `Duyệt chứng từ ${cndnNo} thành công`,
    rejectSuccess: (cndnNo: string) => `Từ chối chứng từ ${cndnNo} thành công`,
    invoiceSuccess: (cndnNo: string) =>
      `Lập hóa đơn cho chứng từ ${cndnNo} thành công`,
  },
  WeighingGoods: {
    updateHeaderSuccess: 'Cập nhật thành công',
    headerIsUndefined: 'Không tìm thấy thông tin phiếu cân',
    postWeighItemSuccess: 'Cập nhật lần cân thành công',
    deleteItemSuccess: 'Xoá lần cân thành công',
    uploadReturnSuccess: (title: string, weightNo: string) =>
      `${title} phiếu cân ${weightNo} thành công.`,
    deleteHeaderSuccess: 'Xoá phiếu cân thành công',
  },
};
export default AppString;
