import {IVersion} from './DatabaseType';

const DataMigration: IVersion[] = [
  {
    version: 1,
    statement: `CREATE TABLE IF NOT EXISTS  PRODUCT_STOCK(
      PRODUCTID TEXT PRIMARY KEY NOT NULL,
      NAME_VN TEXT,
      NAME_EN TEXT,
      MEASURECODE TEXT,
      DESCRIPTION TEXT,
      PRODTYPE INTEGER,
      ACTIVE INTEGER,
      VAT NUMERIC,
      USERCREATE TEXT,
      CREATEDATE TEXT
    );`,
  },
  {
    version: 2,
    statement: `CREATE TABLE IF NOT EXISTS SCALE_HEADER (
      SCALEID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
      SCALEDATE  TEXT,
      DONO TEXT NOT NULL UNIQUE,
      TRUCKNO TEXT,
      ARRIVALTIME TEXT,
      DEPARTTIME TEXT,
      KMSTART NUMERIC,
      KMARRIVED NUMERIC,
      WEIGHMAN TEXT NOT NULL,
      REMAKS TEXT,
      USERNAME TEXT NOT NULL,
      CREATEDBY TEXT NOT NULL,
      UNITID TEXT NOT NULL,
      CUSTID TEXT NOT NULL,
      CUSTNAME TEXT,
      CUSTADD TEXT,
      WEIGHTTYPE INTEGER,
      SEALNUMBER TEXT,
      SEALCONDITION TEXT,
      EVENIFEXCESSCO INTEGER DEFAULT 0 NOT NULL, -- VUOT TRONG LUONG

      SUM_WEIGHT NUMERIC,
      SUM_QTY NUMERIC,
      LOCATIONNAME TEXT,

      IS_UPLOADED INTEGER DEFAULT 0 NOT NULL,
      IS_LOCKED NUMBER DEFAULT 0,
      SCALE_ONLINE_ID NUMBER,
      DATE_TO_UPLOADED TEXT
    );`,
  },
  {
    version: 3,
    statement: `CREATE TABLE IF NOT EXISTS SCALE_DETAIL (
      ID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
      SCALEID  INTEGER NOT NULL,
      PRODUCTCODE TEXT NOT NULL,
      PRODUCTNAME TEXT,
      FLOCKID TEXT,
      FLOCKNAME  TEXT,
      MEASURE TEXT,
      QTY INTEGER,
      PWEIGHT NUMERIC,
      GWEIGHT NUMERIC,
      NWEIGHT NUMERIC,
      AVGBW NUMERIC,	
      REMARKS TEXT,
      WHID INTEGER,
      CREATEDBY TEXT,
      WEIGHTCONNECTID INTEGER,	
      PRODUCTDOWN INTEGER,
      PRODUCTDOWNDESC TEXT,
      FOREIGN KEY (SCALEID) REFERENCES SCALE_HEADER(SCALEID)
    );`,
  },
  {
    version: 4,
    statement: `CREATE TABLE IF NOT EXISTS DELIVERY_ORDER (
          DONO TEXT NOT NULL UNIQUE PRIMARY KEY,
          DODATE TEXT,
          SONO TEXT,
          UNITID TEXT,
          CUSTNAME TEXT,
          CUSTID TEXT,
          CUSTADDRESS TEXT,
          TRUCK_NO TEXT,
          BW_TOTAL NUMERIC,
          TOTALQTY NUMERIC,
          LOCATIONNAME TEXT,
          IS_HAS_SCALE_TEMP INTEGER DEFAULT 0,
          CREATED_BY TEXT
      );`,
  },
  {
    version: 5,
    statement: `CREATE TABLE IF NOT EXISTS  BLUETOOTH_PRINTER(
      MAC_ADDRESS TEXT PRIMARY KEY NOT NULL UNIQUE,
      NAME TEXT,
      REMIND_NAME TEXT,
      IS_DEFAULT INTEGER DEFAULT 0,
      TYPE TEXT  DEFAULT 'START' -- STAR, ETC
    )`,
  },
];

// eslint-disable-next-line import/prefer-default-export
export {DataMigration};
